# nnictl experiment export ssY3qqgD -f ./csv/Enz.csv --type "csv"

authorName: Zhangyang Gao
experimentName: ex_DD
debug: True
trialConcurrency: 20
maxExecDuration: 12h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_DD.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: BatchTuner

trial:
  command: python main.py 
  codeDir: ../
  gpuNum: 1

localConfig:
  gpuIndices: "4,3"
  maxTrialNumPerGpu: 5
  useActiveGpu: False