authorName: Zhangyang Gao
experimentName: ex_DD
debug: True
trialConcurrency: 30
maxExecDuration: 12h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_DD.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize

trial:
  command: python main.py 
  codeDir: .
  gpuNum: 1

localConfig:
  gpuIndices: "0,3,4,5,6,7"
  maxTrialNumPerGpu: 5
  useActiveGpu: False