authorName: Zhangyang Gao
experimentName: ex_PROTEINS
debug: True
trialConcurrency: 35
maxExecDuration: 12h
maxTrialNum: 300
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_Pro.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize

trial:
  command: python main.py 
  codeDir: .
  gpuNum: 1

localConfig:
  gpuIndices: 1,2,3,4,5,6,7
  maxTrialNumPerGpu: 5
  useActiveGpu: False