authorName: Zhangyang Gao
experimentName: ex_Mutagenicity
debug: True
trialConcurrency: 20
maxExecDuration: 12h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_Mut.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize

trial:
  command: python main.py 
  codeDir: .
  gpuNum: 1

localConfig:
  gpuIndices: "5,6"
  maxTrialNumPerGpu: 10
  useActiveGpu: False