# nnictl experiment export ssY3qqgD -f ./csv/Enz.csv --type "csv"

authorName: Zhangyang Gao
experimentName: ex_DD
debug: True
trialConcurrency: 2
maxExecDuration: 12h
maxTrialNum: 500
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_cmp.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: BatchTuner

trial:
  command: python main.py 
  codeDir: ../
  gpuNum: 1

localConfig:
  gpuIndices: "0,1,3,4,5"
  maxTrialNumPerGpu: 3
  useActiveGpu: False