authorName: Zhangyang Gao
experimentName: ex_NCI1
debug: True
trialConcurrency: 20
maxExecDuration: 12h
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_NCI1.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize

trial:
  command: python ../main.py 
  codeDir: .
  gpuNum: 1

localConfig:
  gpuIndices: "4,5"
  maxTrialNumPerGpu: 10
  useActiveGpu: False